CREATE TABLE IF NOT EXISTS bookings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    mobileNumber VARCHAR(20) NOT NULL,
    date DATE NOT NULL,
    timeSlot VARCHAR(20) NOT NULL,
    instaId VARCHAR(50) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);